title: pHSmile
picture: pHSmile.png
logo: pHSmile.png
picture: blockdiagram.png
#description text below image 
show_download: true
#theme:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
