title: Non-Invasive Diagnostic Device for the Detection and Monitoring of Bacterial Acidogenesis on Dental Enamel
logo: pHSmile.png
#description text below image 
show_download: true
#theme:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
