title: pHSmile
picture: pHSmile.png
logo: pHSmile.png
picture: Screenshot 2024-10-21 8.30.40 PM.png
#description text below image 
show_download: true
#theme:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
